apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{ template "demochat.deploymentName" .}}
  name: {{ template "demochat.deploymentName" .}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      run: {{ template "demochat.fullname" .}}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.max }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: {{ template "demochat.fullname" .}}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: {{ template "demochat.fullname" .}}
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ template "demochat.serviceName" . }}
  name: {{ template "demochat.serviceName" . }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
    nodePort: {{ .Values.nodePort }}
  selector:
    run: {{ template "demochat.fullname" . }}
  type: NodePort


